workspace 'IOSPlayer.xcworkspace'
use_frameworks!
target 'IOSPlayer' do
    platform :ios, '9.0'
    project 'IOSPlayer/IOSPlayer.xcodeproj'
    pod 'CocoaMQTT'
end
target 'XYRemoterKit' do
    platform :ios, '9.0'
    project 'XYRemoter/XYRemoter.xcodeproj'
    pod 'CocoaMQTT' 
end
target 'XYRemoter' do
    platform :ios, '9.0'
    project 'XYRemoter/XYRemoter.xcodeproj'
    pod 'CocoaMQTT'
end
